updated comment, blog and createpost section
Macbright007/robotsBlog pull request #4
Opened 2022-06-19 14:52 UTC by Macbright007

2022-06-19 16:32 UTC, Asylcreek requested changes

2022-06-19 16:32 UTC, Asylcreek commented on src/components/SinglePost.js
> +      setComments(newCommentList)
You can use the `setState function arg` to achieve the same functionality

2022-06-19 16:32 UTC, Asylcreek commented on src/components/SinglePost.js
> +      const result = await Axios.post('https://blogpostapi1.herokuapp.com/comment', {
You saved your url in a variable and you are not using it

2022-06-19 16:32 UTC, Asylcreek commented on src/components/SinglePost.js
> +            `https://blogpostapi1.herokuapp.com/${params.id}`
You saved your url in a variable and you are not using it

2022-06-19 16:32 UTC, Asylcreek commented on src/components/SinglePost.js
> +            `https://blogpostapi1.herokuapp.com/comment/all_comments/${params.id}`
You saved your url in a variable and you are not using it

2022-06-20 18:03 UTC, Macbright007 commented on src/components/SinglePost.js
> +      setComments(newCommentList)
i dont get this please

2022-06-20 18:14 UTC, Macbright007 commented on src/components/SinglePost.js
> +      const result = await Axios.post('https://blogpostapi1.herokuapp.com/comment', {
okay

2022-06-21 14:21 UTC, Asylcreek commented on src/components/SinglePost.js
> +      setComments(newCommentList)
`setComment((prev) => ([...prev, newComment]))`

2022-06-21 14:22 UTC, Asylcreek approved these changes

2022-06-21 14:25 UTC, Macbright007 commented on src/components/SinglePost.js
> +      setComments(newCommentList)
on line 22 or 23??

2022-06-21 14:26 UTC, Macbright007 commented
can i merge them now?

2022-06-21 14:38 UTC, Asylcreek commented on src/components/SinglePost.js
> +      setComments(newCommentList)
Lines 21 - 25

2022-06-21 14:39 UTC, Asylcreek commented
Sure.

2022-06-21 14:43 UTC, merged